// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD301f-bRulo0CDn_ixWovmwAUQgssI_y8',
    appId: '1:500294261691:web:5e6d714b4a25d55d32c29e',
    messagingSenderId: '500294261691',
    projectId: 'workouttrackerdb',
    authDomain: 'workouttrackerdb.firebaseapp.com',
    databaseURL:
        'https://workouttrackerdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'workouttrackerdb.appspot.com',
    measurementId: 'G-XDPLTX91EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf00a-XkYJFuhz3DLRpHOKA4RwTQR-v9s',
    appId: '1:500294261691:android:df27eb9242869b9c32c29e',
    messagingSenderId: '500294261691',
    projectId: 'workouttrackerdb',
    databaseURL:
        'https://workouttrackerdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'workouttrackerdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Imt0JqMjcrsCmohrbE4nwPMi04t4G6Q',
    appId: '1:500294261691:ios:0fb8c453f807266532c29e',
    messagingSenderId: '500294261691',
    projectId: 'workouttrackerdb',
    databaseURL:
        'https://workouttrackerdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'workouttrackerdb.appspot.com',
    iosClientId:
        '500294261691-3e1h2a2il9bvetbfegn1es1rtm79j5k6.apps.googleusercontent.com',
    iosBundleId: 'workout.tracker',
  );
}
