name: workout_tracker
description: workout_tracker

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  #Firebase
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_database: ^9.0.6
  #Google SignIn
  google_sign_in: ^5.2.3
  #Facebook SignIn
  flutter_facebook_auth: ^4.0.1

  #State Management tool
  provider: ^6.0.2

  font_awesome_flutter: ^9.2.0
  circular_countdown_timer: ^0.2.0
  snack: ^2.0.0
  cached_network_image: ^3.2.0
  dropdown_button2: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/all_icons/abdominal_images/icons/
    - assets/all_icons/back_images/icons/
    - assets/all_icons/biceps_images/icons/
    - assets/all_icons/chest_images/icons/
    - assets/all_icons/forearms_images/icons/
    - assets/all_icons/legs_images/icons/
    - assets/all_icons/shoulders_images/icons/
    - assets/all_icons/triceps_images/icons/
    - assets/
