name: workout_tracker
description: workout_tracker

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  #Firebase
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5

  #State Management tool
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
