// Mocks generated by Mockito 5.1.0 from annotations
// in workout_tracker/test/unit_tests/database_unit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/utils/firebase/firebase_service.dart' as _i2;
import 'package:workout_tracker/utils/models/user_database.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<dynamic, dynamic>?> getData(String? dataType) =>
      (super.noSuchMethod(Invocation.method(#getData, [dataType]), returnValue: Future<Map<dynamic, dynamic>?>.value())
          as _i3.Future<Map<dynamic, dynamic>?>);
  @override
  _i3.Future<Map<String, dynamic>> createUserBeforeDetails(String? uid, String? email) =>
      (super.noSuchMethod(Invocation.method(#createUserBeforeDetails, [uid, email]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool> removeUserBasedOnUID(String? uid) =>
      (super.noSuchMethod(Invocation.method(#removeUserBasedOnUID, [uid]), returnValue: Future<bool>.value(false))
          as _i3.Future<bool>);
  @override
  _i3.Future<Map<String, dynamic>> createUserWithFullDetails(String? uid, String? email, String? name, String? surname,
          String? sex, int? age, double? weight, double? height, _i4.WeightMetric? weightType) =>
      (super.noSuchMethod(
          Invocation.method(
              #createUserWithFullDetails, [uid, email, name, surname, sex, age, weight, height, weightType]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool?> changeUserWeight(String? uid, double? newWeight) =>
      (super.noSuchMethod(Invocation.method(#changeUserWeight, [uid, newWeight]), returnValue: Future<bool?>.value())
          as _i3.Future<bool?>);
  @override
  _i3.Future<Map<String, dynamic>> createNewExercise(String? userUid, String? exerciseTitle,
          String? exerciseDescription, String? exerciseCategory, String? exerciseBodyType, String? idExercise) =>
      (super.noSuchMethod(
          Invocation.method(#createNewExercise,
              [userUid, exerciseTitle, exerciseDescription, exerciseCategory, exerciseBodyType, idExercise]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool?> removeExerciseBasedOnId(String? exerciseID) =>
      (super.noSuchMethod(Invocation.method(#removeExerciseBasedOnId, [exerciseID]), returnValue: Future<bool?>.value())
          as _i3.Future<bool?>);
  @override
  _i3.Future<Map<String, dynamic>> addWorkoutToHistory(String? name, String? notes, String? startTime,
          String? finalDuration, Map<String, dynamic>? exercisesAndSets, String? idHistory) =>
      (super.noSuchMethod(
          Invocation.method(#addWorkoutToHistory, [name, notes, startTime, finalDuration, exercisesAndSets, idHistory]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool> removeHistory(String? historyID) =>
      (super.noSuchMethod(Invocation.method(#removeHistory, [historyID]), returnValue: Future<bool>.value(false))
          as _i3.Future<bool>);
  @override
  _i3.Future<Map<String, dynamic>> addWorkoutTemplate(
          String? templateID, String? templateName, String? templateNotes, Map<String, dynamic>? exercisesAndSets) =>
      (super.noSuchMethod(
          Invocation.method(#addWorkoutTemplate, [templateID, templateName, templateNotes, exercisesAndSets]),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<bool> removeTemplate(String? templateId) =>
      (super.noSuchMethod(Invocation.method(#removeTemplate, [templateId]), returnValue: Future<bool>.value(false))
          as _i3.Future<bool>);
}
