name: CI/CD - check quality, tests and android build.
on:
  push:

jobs:
  run_analysis:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run analysis
        run: flutter analyze

  run_format:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

        # Check for any formatting issues in the code (line-length 120)
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed .

  run_tests:
    # Quality check must be completed successfully
    needs: [run_analysis, run_format]
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

    # Get flutter dependencies.
      - name: Get dependencies.
        run: flutter pub get

    # Run widget tests for project.
      - name: Run flutter tests.
        run: flutter test

  build_android_apk:
    # Quality check must be completed successfully
    needs: [run_tests]
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Install java for android apk build
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Run Android apk build
      - name: Build flutter apk
        run: flutter build apk --release

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk